import type { RegisteredModel } from '@atlas-vnext/contracts';

/**
 * Declarative catalogue. Adding a model is a data change, not a router rewrite.
 * Health is overwritten at composition time from credentials / probes.
 * upstreamId is the provider API model id when it differs from the registry key.
 */
export const MODEL_CATALOGUE: RegisteredModel[] = [
  {
    provider: 'openai',
    model: 'gpt-4o',
    label: 'GPT-4o',
    upstreamId: 'gpt-4o',
    capabilities: { text: true, reasoning: false, tools: true, vision: true, code: true },
    contextWindow: 128_000,
    costClass: 'medium',
    latencyClass: 'fast',
    locality: 'cloud',
    health: 'configured',
    privacyEligibility: 'any',
    runtimeRequirements: ['openai'],
  },
  {
    provider: 'anthropic',
    model: 'claude-sonnet',
    label: 'Claude Sonnet',
    upstreamId: 'claude-sonnet-4-5',
    capabilities: { text: true, reasoning: true, tools: true, vision: true, code: true },
    contextWindow: 200_000,
    costClass: 'high',
    latencyClass: 'medium',
    locality: 'cloud',
    health: 'configured',
    privacyEligibility: 'any',
    runtimeRequirements: ['anthropic'],
  },
  {
    provider: 'gemini',
    model: 'flash',
    label: 'Gemini Flash',
    upstreamId: 'gemini-2.0-flash',
    capabilities: { text: true, reasoning: false, tools: true, vision: true, code: true },
    contextWindow: 128_000,
    costClass: 'low',
    latencyClass: 'fast',
    locality: 'cloud',
    health: 'configured',
    privacyEligibility: 'any',
    runtimeRequirements: ['gemini'],
  },
  {
    provider: 'ollama',
    model: 'llama3.2',
    label: 'Llama 3.2',
    upstreamId: 'llama3.2',
    capabilities: { text: true, reasoning: false, tools: true, vision: false, code: false },
    contextWindow: 8192,
    costClass: 'free',
    latencyClass: 'fast',
    locality: 'local',
    health: 'configured',
    privacyEligibility: 'local_only',
    runtimeRequirements: ['ollama'],
  },
  {
    provider: 'venice',
    model: 'uncensored',
    label: 'Venice Uncensored',
    upstreamId: 'venice-uncensored',
    capabilities: { text: true, reasoning: false, tools: false, vision: false, code: false },
    contextWindow: 32_768,
    costClass: 'low',
    latencyClass: 'medium',
    locality: 'cloud',
    health: 'configured',
    privacyEligibility: 'any',
    runtimeRequirements: ['venice'],
  },
  {
    provider: 'runpod',
    model: 'placeholder',
    label: 'RunPod (not implemented)',
    capabilities: { text: true, reasoning: false, tools: false, vision: false, code: false },
    contextWindow: 8192,
    costClass: 'medium',
    latencyClass: 'slow',
    locality: 'cloud',
    health: 'unavailable',
    privacyEligibility: 'any',
    runtimeRequirements: ['runpod'],
  },
  {
    provider: 'openai',
    model: 'o3-mini',
    label: 'o3-mini',
    upstreamId: 'o3-mini',
    capabilities: { text: true, reasoning: true, tools: true, vision: false, code: true },
    contextWindow: 200_000,
    costClass: 'high',
    latencyClass: 'medium',
    locality: 'cloud',
    health: 'configured',
    privacyEligibility: 'any',
    runtimeRequirements: ['openai'],
  },
  {
    provider: 'anthropic',
    model: 'claude-haiku',
    label: 'Claude Haiku',
    upstreamId: 'claude-3-5-haiku-latest',
    capabilities: { text: true, reasoning: false, tools: true, vision: true, code: true },
    contextWindow: 200_000,
    costClass: 'low',
    latencyClass: 'fast',
    locality: 'cloud',
    health: 'configured',
    privacyEligibility: 'any',
    runtimeRequirements: ['anthropic'],
  },
  {
    provider: 'forge',
    model: 'placeholder',
    label: 'Forge / Hetzner (not implemented)',
    capabilities: { text: true, reasoning: false, tools: false, vision: false, code: false },
    contextWindow: 8192,
    costClass: 'medium',
    latencyClass: 'slow',
    locality: 'cloud',
    health: 'unavailable',
    privacyEligibility: 'any',
    runtimeRequirements: ['forge'],
  },
  {
    provider: 'hetzner',
    model: 'placeholder',
    label: 'Hetzner (not implemented)',
    capabilities: { text: true, reasoning: false, tools: false, vision: false, code: false },
    contextWindow: 8192,
    costClass: 'medium',
    latencyClass: 'slow',
    locality: 'cloud',
    health: 'unavailable',
    privacyEligibility: 'any',
    runtimeRequirements: ['hetzner'],
  },
];

/** @deprecated use MODEL_CATALOGUE */
export const DEV_CATALOGUE = MODEL_CATALOGUE;
