import type { RegisteredModel } from '@atlas-vnext/contracts';

/**
 * Declarative catalogue. Adding a model is a data change, not a router rewrite.
 * Health is overwritten at composition time from credentials / probes.
 * upstreamId is the provider API model id when it differs from the registry key.
 *
 * Grok IDs are the current xAI canonical chat models (docs.x.ai/developers/models).
 * `grok-build` is the catalogue alias for upstream `grok-build-0.1` (docs also list
 * grok-code-fast-1). Do not invent additional model IDs.
 * Forge is the private inference service on Hetzner — one provider, not two catalogues.
 * RunPod is a single on-demand GPU profile, not a fake placeholder model.
 */
export const MODEL_CATALOGUE: RegisteredModel[] = [
  {
    provider: 'openai',
    model: 'gpt-4o',
    label: 'GPT-4o',
    upstreamId: 'gpt-4o',
    capabilities: { text: true, reasoning: false, tools: true, vision: true, code: true },
    contextWindow: 128_000,
    costClass: 'medium',
    latencyClass: 'fast',
    locality: 'public_cloud',
    runtimeClass: 'always_available',
    health: 'configured',
    privacyEligibility: 'any',
    runtimeRequirements: ['openai'],
  },
  {
    provider: 'anthropic',
    model: 'claude-sonnet',
    label: 'Claude Sonnet',
    upstreamId: 'claude-sonnet-4-5',
    capabilities: { text: true, reasoning: true, tools: true, vision: true, code: true },
    contextWindow: 200_000,
    costClass: 'high',
    latencyClass: 'medium',
    locality: 'public_cloud',
    runtimeClass: 'always_available',
    health: 'configured',
    privacyEligibility: 'any',
    runtimeRequirements: ['anthropic'],
  },
  {
    provider: 'gemini',
    model: 'flash',
    label: 'Gemini Flash',
    upstreamId: 'gemini-2.0-flash',
    capabilities: { text: true, reasoning: false, tools: true, vision: true, code: true },
    contextWindow: 128_000,
    costClass: 'low',
    latencyClass: 'fast',
    locality: 'public_cloud',
    runtimeClass: 'always_available',
    health: 'configured',
    privacyEligibility: 'any',
    runtimeRequirements: ['gemini'],
  },
  {
    provider: 'ollama',
    model: 'llama3.2',
    label: 'Llama 3.2',
    upstreamId: 'llama3.2',
    capabilities: { text: true, reasoning: false, tools: true, vision: false, code: false },
    contextWindow: 8192,
    costClass: 'free',
    latencyClass: 'fast',
    locality: 'local',
    runtimeClass: 'always_available',
    health: 'configured',
    privacyEligibility: 'local_only',
    runtimeRequirements: ['ollama'],
  },
  {
    provider: 'venice',
    model: 'uncensored',
    label: 'Venice Uncensored',
    upstreamId: 'venice-uncensored',
    capabilities: { text: true, reasoning: false, tools: false, vision: false, code: false },
    contextWindow: 32_768,
    costClass: 'low',
    latencyClass: 'medium',
    locality: 'public_cloud',
    runtimeClass: 'always_available',
    health: 'configured',
    privacyEligibility: 'any',
    runtimeRequirements: ['venice'],
  },
  {
    provider: 'openai',
    model: 'o3-mini',
    label: 'o3-mini',
    upstreamId: 'o3-mini',
    capabilities: { text: true, reasoning: true, tools: true, vision: false, code: true },
    contextWindow: 200_000,
    costClass: 'high',
    latencyClass: 'medium',
    locality: 'public_cloud',
    runtimeClass: 'always_available',
    health: 'configured',
    privacyEligibility: 'any',
    runtimeRequirements: ['openai'],
  },
  {
    provider: 'anthropic',
    model: 'claude-haiku',
    label: 'Claude Haiku',
    upstreamId: 'claude-3-5-haiku-latest',
    capabilities: { text: true, reasoning: false, tools: true, vision: true, code: true },
    contextWindow: 200_000,
    costClass: 'low',
    latencyClass: 'fast',
    locality: 'public_cloud',
    runtimeClass: 'always_available',
    health: 'configured',
    privacyEligibility: 'any',
    runtimeRequirements: ['anthropic'],
  },
  {
    provider: 'xai',
    model: 'grok-4.6',
    label: 'Grok 4.6',
    upstreamId: 'grok-4.6',
    capabilities: { text: true, reasoning: true, tools: true, vision: true, code: true },
    contextWindow: 500_000,
    costClass: 'high',
    latencyClass: 'medium',
    locality: 'public_cloud',
    runtimeClass: 'always_available',
    health: 'configured',
    privacyEligibility: 'any',
    runtimeRequirements: ['xai'],
  },
  {
    provider: 'xai',
    model: 'grok-4.3',
    label: 'Grok 4.3',
    upstreamId: 'grok-4.3',
    capabilities: { text: true, reasoning: true, tools: true, vision: true, code: true },
    contextWindow: 1_000_000,
    costClass: 'medium',
    latencyClass: 'medium',
    locality: 'public_cloud',
    runtimeClass: 'always_available',
    health: 'configured',
    privacyEligibility: 'any',
    runtimeRequirements: ['xai'],
  },
  {
    provider: 'xai',
    model: 'grok-4.20-fast',
    label: 'Grok 4.20 Fast',
    upstreamId: 'grok-4.20-0309-non-reasoning',
    capabilities: { text: true, reasoning: false, tools: true, vision: true, code: true },
    contextWindow: 1_000_000,
    costClass: 'medium',
    latencyClass: 'fast',
    locality: 'public_cloud',
    runtimeClass: 'always_available',
    health: 'configured',
    privacyEligibility: 'any',
    runtimeRequirements: ['xai'],
  },
  {
    provider: 'xai',
    model: 'grok-4.20-reason',
    label: 'Grok 4.20 Reasoning',
    upstreamId: 'grok-4.20-0309-reasoning',
    capabilities: { text: true, reasoning: true, tools: true, vision: true, code: true },
    contextWindow: 1_000_000,
    costClass: 'high',
    latencyClass: 'medium',
    locality: 'public_cloud',
    runtimeClass: 'always_available',
    health: 'configured',
    privacyEligibility: 'any',
    runtimeRequirements: ['xai'],
  },
  {
    provider: 'xai',
    model: 'grok-build',
    label: 'Grok Build',
    upstreamId: 'grok-build-0.1',
    // docs.x.ai/developers/models/grok-code-fast-1 — model id grok-build-0.1:
    // text + image input → text, function calling, structured outputs, reasoning, agentic coding.
    capabilities: { text: true, reasoning: true, tools: true, vision: true, code: true },
    contextWindow: 256_000,
    costClass: 'medium',
    latencyClass: 'fast',
    locality: 'public_cloud',
    runtimeClass: 'always_available',
    health: 'configured',
    privacyEligibility: 'any',
    runtimeRequirements: ['xai'],
  },
  {
    provider: 'forge',
    model: 'llama3.2',
    label: 'Forge Llama 3.2',
    upstreamId: 'llama3.2',
    capabilities: { text: true, reasoning: false, tools: true, vision: false, code: false },
    contextWindow: 8192,
    costClass: 'free',
    latencyClass: 'medium',
    locality: 'private_cloud',
    runtimeClass: 'private_hosted',
    health: 'configured',
    privacyEligibility: 'any',
    runtimeRequirements: ['forge'],
  },
  {
    provider: 'forge',
    model: 'qwen3',
    label: 'Forge Qwen 3',
    upstreamId: 'qwen3:4b-instruct',
    capabilities: { text: true, reasoning: false, tools: true, vision: false, code: true },
    contextWindow: 32_768,
    costClass: 'free',
    latencyClass: 'fast',
    locality: 'private_cloud',
    runtimeClass: 'private_hosted',
    health: 'configured',
    privacyEligibility: 'any',
    runtimeRequirements: ['forge'],
  },
  {
    provider: 'runpod',
    model: 'llm',
    label: 'RunPod shared LLM',
    upstreamId: 'llm',
    capabilities: { text: true, reasoning: true, tools: true, vision: false, code: true },
    contextWindow: 32_768,
    costClass: 'high',
    latencyClass: 'slow',
    locality: 'private_cloud',
    runtimeClass: 'expensive_burst',
    health: 'configured',
    privacyEligibility: 'any',
    runtimeRequirements: ['runpod'],
  },
];

/** @deprecated use MODEL_CATALOGUE */
export const DEV_CATALOGUE = MODEL_CATALOGUE;
