import type { CapabilityScope, ToolCategory, ToolDefinition } from '@atlas-vnext/contracts';

function def(
  partial: Omit<ToolDefinition, 'version' | 'timeoutMs' | 'cancelSupported' | 'idempotency'> & {
    timeoutMs?: number;
    cancelSupported?: boolean;
    idempotency?: ToolDefinition['idempotency'];
  },
): ToolDefinition {
  return {
    version: '1.0.0',
    timeoutMs: partial.timeoutMs ?? 15_000,
    cancelSupported: partial.cancelSupported ?? false,
    idempotency: partial.idempotency ?? (partial.sideEffectClass === 'none' ? 'none' : 'keyed'),
    ...partial,
  };
}

const objectSchema = (properties: Record<string, unknown>, required: string[] = []) => ({
  type: 'object',
  additionalProperties: false,
  properties,
  required,
});

export const PLATFORM_TOOL_CATALOGUE: ToolDefinition[] = [
  def({
    id: 'retrieval.search',
    title: 'Retrieval search',
    description: 'Read-only federated web search across configured engines.',
    category: 'retrieval_readonly' satisfies ToolCategory,
    adapter: 'retrieval.readonly',
    requiredCapabilities: ['network.public', 'tool.invoke.readonly'],
    sideEffectClass: 'none',
    approvalPolicy: 'none',
    inputSchema: objectSchema({ query: { type: 'string', minLength: 1 } }, ['query']),
    outputSchema: objectSchema({ hits: { type: 'array' } }),
  }),
  def({
    id: 'fs.read',
    title: 'Read file',
    description: 'Read a file inside the workspace jail.',
    category: 'fs_read',
    adapter: 'fs.read',
    requiredCapabilities: ['filesystem.read', 'file.read'],
    sideEffectClass: 'none',
    approvalPolicy: 'none',
    inputSchema: objectSchema({ path: { type: 'string', minLength: 1 } }, ['path']),
    outputSchema: objectSchema({ path: { type: 'string' }, content: { type: 'string' }, bytes: { type: 'number' } }),
  }),
  def({
    id: 'fs.write',
    title: 'Write file',
    description: 'Write a file inside the workspace jail.',
    category: 'fs_write',
    adapter: 'fs.write',
    requiredCapabilities: ['filesystem.write', 'file.write', 'tool.invoke.external_write'],
    sideEffectClass: 'idempotent',
    approvalPolicy: 'required',
    inputSchema: objectSchema({ path: { type: 'string', minLength: 1 }, content: { type: 'string' } }, ['path', 'content']),
    outputSchema: objectSchema({ path: { type: 'string' }, written: { type: 'boolean' } }),
  }),
  def({
    id: 'browser.navigate',
    title: 'Browser navigate',
    description: 'Navigate and read a live public page.',
    category: 'browser_nav_read',
    adapter: 'browser.navigate',
    requiredCapabilities: ['browser.read', 'network.public'],
    sideEffectClass: 'none',
    approvalPolicy: 'none',
    inputSchema: objectSchema({ url: { type: 'string', minLength: 1 } }, ['url']),
    outputSchema: objectSchema({ url: { type: 'string' }, title: { type: 'string' }, body: { type: 'string' } }),
  }),
  def({
    id: 'browser.submit',
    title: 'Browser submit',
    description: 'Submit a form in the mock browser.',
    category: 'browser_state_changing',
    adapter: 'browser.submit',
    requiredCapabilities: ['browser.submit', 'tool.invoke.external_write'],
    sideEffectClass: 'uncertain_external',
    approvalPolicy: 'required',
    inputSchema: objectSchema({ url: { type: 'string', minLength: 1 } }, ['url']),
    outputSchema: objectSchema({ submitted: { type: 'boolean' }, url: { type: 'string' } }),
  }),
  def({
    id: 'api.read',
    title: 'HTTP GET',
    description: 'Read-only HTTP GET of a public URL.',
    category: 'external_api_read',
    adapter: 'api.read',
    requiredCapabilities: ['network.public', 'tool.invoke.readonly'],
    sideEffectClass: 'none',
    approvalPolicy: 'none',
    inputSchema: objectSchema({ url: { type: 'string', minLength: 1 } }, ['url']),
    outputSchema: objectSchema({ status: { type: 'number' } }),
  }),
  def({
    id: 'api.mutate',
    title: 'HTTP mutate',
    description: 'Mock HTTP mutation.',
    category: 'external_api_mutation',
    adapter: 'api.mutate',
    requiredCapabilities: ['network.public', 'tool.invoke.external_write'],
    sideEffectClass: 'uncertain_external',
    approvalPolicy: 'required',
    inputSchema: objectSchema(
      { url: { type: 'string', minLength: 1 }, method: { type: 'string', enum: ['POST', 'PUT', 'PATCH', 'DELETE'] } },
      ['url'],
    ),
    outputSchema: objectSchema({ status: { type: 'number' } }),
  }),
  def({
    id: 'shell.exec',
    title: 'Shell',
    description: 'Bounded process execution inside the workspace jail.',
    category: 'shell_process',
    adapter: 'shell.exec',
    requiredCapabilities: ['shell.execute'],
    sideEffectClass: 'uncertain_external',
    approvalPolicy: 'required',
    cancelSupported: true,
    timeoutMs: 10_000,
    inputSchema: objectSchema({ argv: { type: 'array', items: { type: 'string' }, minItems: 1 }, cwd: { type: 'string' } }, [
      'argv',
    ]),
    outputSchema: objectSchema({ code: { type: 'number' } }),
  }),
  def({
    id: 'code.exec',
    title: 'Code exec',
    description: 'Bounded in-process expression evaluation.',
    category: 'code_exec',
    adapter: 'code.exec',
    requiredCapabilities: ['code.execute'],
    sideEffectClass: 'none',
    approvalPolicy: 'required',
    inputSchema: objectSchema({ source: { type: 'string', minLength: 1 } }, ['source']),
    outputSchema: objectSchema({ result: {} }),
  }),
  def({
    id: 'job.run',
    title: 'Long-running job',
    description: 'Enqueue work on the shared job engine. Does not start RunPod.',
    category: 'long_running_job',
    adapter: 'job.long_running',
    requiredCapabilities: ['tool.invoke'],
    sideEffectClass: 'idempotent',
    approvalPolicy: 'none',
    cancelSupported: true,
    inputSchema: objectSchema({ label: { type: 'string' } }),
    outputSchema: objectSchema({ jobId: { type: 'string' } }),
  }),
  def({
    id: 'project.file_op',
    title: 'Project file op',
    description: 'Project/file/artefact operation inside the jail.',
    category: 'project_file_artifact',
    adapter: 'project.file_op',
    requiredCapabilities: ['project.read', 'file.read'],
    sideEffectClass: 'none',
    approvalPolicy: 'none',
    inputSchema: objectSchema({ op: { type: 'string' }, path: { type: 'string' } }),
    outputSchema: objectSchema({ op: { type: 'string' } }),
  }),
  def({
    id: 'communication.publish',
    title: 'Publish',
    description: 'Publish to an external channel.',
    category: 'communication_publish',
    adapter: 'communication.publish',
    requiredCapabilities: ['publish.external'],
    sideEffectClass: 'uncertain_external',
    approvalPolicy: 'required',
    inputSchema: objectSchema({ channel: { type: 'string', minLength: 1 }, body: { type: 'string' } }, ['channel']),
    outputSchema: objectSchema({ published: { type: 'boolean' } }),
  }),
  def({
    id: 'admin.configure',
    title: 'Admin configure',
    description: 'Administrative configuration. Not implied by other categories.',
    category: 'admin',
    adapter: 'admin.configure',
    requiredCapabilities: ['admin.configure'],
    sideEffectClass: 'idempotent',
    approvalPolicy: 'required',
    inputSchema: objectSchema({ key: { type: 'string', minLength: 1 }, value: { type: 'string' } }, ['key']),
    outputSchema: objectSchema({ applied: { type: 'boolean' } }),
  }),
  def({
    id: 'mock.echo',
    title: 'Mock echo',
    description: 'In-process plugin connector proving E2E without paid credentials.',
    category: 'retrieval_readonly',
    adapter: 'mock.echo',
    pluginId: 'plugin.mock.echo',
    requiredCapabilities: ['tool.invoke.readonly'],
    sideEffectClass: 'none',
    approvalPolicy: 'none',
    inputSchema: objectSchema({ text: { type: 'string' } }),
    outputSchema: objectSchema({ echo: {} }),
  }),
];

export function capabilitiesFor(toolId: string): CapabilityScope[] {
  return (PLATFORM_TOOL_CATALOGUE.find((row) => row.id === toolId)?.requiredCapabilities ?? []) as CapabilityScope[];
}
